export {
  extractMessageText,
  isOutgoingMessage,
  extractAuthor,
  extractTimestamp,
  extractReplyTo,
  parseMessageElement,
  findBubbles,
  getLastMessages,
  parseMessages,
  detectChatType,
  extractChatName,
  buildChatContext,
  extractChatIdFromUrl,
  getCurrentChatIdentity,
  buildChatContextWithIdentity,
} from './parser';
